lab_7/WebLab/config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  resource :session, only: %i[new create]
  get 'session' => 'sessions#destroy'
  resources :users, only: %i[new create]
  resources :reports
end

lab_7/WebLab/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

lab_7/WebLab/app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
end

lab_7/WebLab/app/models/user.rb
class User < ApplicationRecord
    has_many :reports
    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :email, presence: true, uniqueness: true
    validates :password, presence: true
end

lab_7/WebLab/app/controllers/application_controller.rb
require 'digest'
class ApplicationController < ActionController::Base

    private
    def current_user
        @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id].present?
    end

    def user_signed_in?
        current_user.present?
    end

    def hash(password)
        return Digest::SHA256.hexdigest(password.to_s)
    end

    helper_method :current_user, :user_signed_in?, :hash
end

lab_7/WebLab/app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def index
    end
end

lab_7/WebLab/app/controllers/reports_controller.rb
class ReportsController < ApplicationController
    before_action :set_report, only: %i[update show destroy edit]

    def index
        @reports = Report.where(user_id: current_user.id)
    end

    def create
        @report = Report.create(report_params)
        redirect_to reports_path
    end

    def update
        @report.update(report_params)
        redirect_to reports_path
    end

    def destroy
        @report.destroy
    end

    def show
    end

    def new
        @report = Report.new
    end

    def edit
    end

    private
    def report_params
        params.require(:report).permit(:user_id, :title, :description, :grade)
    end

    def set_report
        @report = Report.find(params[:id])
    end
end

lab_7/WebLab/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        user = nil
        if (User.find_by email: params[:email]).nil?
            flash[:alert] = 'Пользователь не найден!'
            redirect_to request.referer
        else
            user = User.find_by email: params[:email]
            if !(user.password.to_s).eql?(hash(params[:password].to_s))
                flash[:alert] = 'Неверный пароль!'
                redirect_to request.referer
            else
                flash[:success] = "С возвращением, #{user.first_name} #{user.last_name}!"
                session[:user_id] = user.id
                redirect_to root_path
            end
        end
    end

    def destroy
        flash[:notice] = 'Пользователь покинул систему!'
        session[:user_id] = nil
        @current_user = nil
        redirect_to root_path
    end
end

lab_7/WebLab/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new user_params
        @user.password = hash(@user.password)
        if @user.save
            session[:user_id] = @user.id
            flash[:success] = "Добро пожаловать, #{@user.first_name} #{@user.last_name}!"
            redirect_to root_path
        else
            flash[:alert] = "Регистрация не прошла успешно!"
            render :new
        end
    end

    private
    def user_params
        params.require(:user).permit(:first_name, :last_name, :email, :password)
    end
end

lab_7/WebLab/app/helpers/application_helper.rb
module ApplicationHelper
end

lab_7/WebLab/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebLab</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

lab_7/WebLab/app/views/pages/index.html.erb
<center>
    <%if flash[:alert]%>
        <font color="red"><%= flash[:alert] %></font>
    <%elsif flash[:success] %>
        <font color="green"><%= flash[:success] %></font>
    <%else%>
        <font color="blue"><%= flash[:notice] %></font>
    <%end%>
    <h1>Добро пожаловать в WebLab!<h2>
    <% if user_signed_in? %>
        <font color="blue"> Вы вошли как: <%= current_user.first_name %> <%= current_user.last_name %> </font>
        <br>
        <%= link_to 'Выйти', '/session', method: :get%>
        <br><br>
        <%= link_to 'К отчетам пользователя', reports_path %>
    <% else %>
        <p>У вас нет аккаунта? Зарегистрируйтесь!</p>
        <%= link_to 'Регистрация', new_user_path %>
        <br><br>
        <p>Есть аккаунт? Авторизуйтесь!</p>
        <%= link_to 'Войти', new_session_path%>
    <% end %>
</center>

lab_7/WebLab/app/views/reports/edit.html.erb
<div align="center">
    <h2> Добавление оценки </h2>

    <%=form_with model: @report do |f| %>
        <p><%=f.radio_button :grade, 'A (100-90)'%>
        <%=f.label :grade_a, 'A (100-90)'%></p>
        <p><%=f.radio_button :grade, 'B (89-82)'%>
        <%=f.label :grade_b, 'B (89-82)'%></p>
        <p><%=f.radio_button :grade, 'C (81-75)'%>
        <%=f.label :grade_c, 'C (81-75)'%></p>
        <p><%=f.radio_button :grade, 'D (74-69)'%>
        <%=f.label :grade_d, 'D (74-69)'%></p>
        <p><%=f.radio_button :grade, 'E (68-60)'%>
        <%=f.label :grade_e, 'E (68-60)'%></p>
        <p><%=f.radio_button :grade, 'FX (59-35)'%>
        <%=f.label :grade_fx, 'FX (59-35)'%></p>
        <p><%=f.radio_button :grade, 'F (34-1)'%>
        <%=f.label :grade_f, 'F (34-1)'%></p>
        <p><%=f.submit 'Оценить'%></p>
    <%end%>
</div>
<br>
<%=button_to '⇐ Отмена', reports_path, method: :get%>

lab_7/WebLab/app/views/reports/index.html.erb
<%=button_to '⇐ На Главную', root_path, method: :get%>
<p style="font-size:3; color:blue; margin-right:80px" align="right"><%=current_user.first_name%> <%=current_user.last_name%></p>
<a data-method="get" href="/session" style="float:right; margin-right:80px">Выйти</a><br>
<h1 align="center"> Выполненные работы </h1>
<hr>
<p align="center">Отчет на <%= Time.now %></p>
<hr>

<%# <%=button_to '+ Добавить работу', %>
<button onclick="location.href = 'reports/new'"> + Добавить работу </button>
<br><br>

<% @reports.each do |r| %>
    <h3><%= r.title %></h3>
    <p><%= r.description %></p>
    <div style="display:flex">
        <%if (r.grade).eql?(nil) || (r.grade).eql?('')%>
            <%= button_to '✔ Оценить работу', edit_report_path(r.id), method: :get%>
        <%else%>
            <b>Оценка: <%=r.grade%></b>
        <%end%> &nbsp;&nbsp;|&nbsp;&nbsp;
        <%=button_to '☒ Удалить работу', report_path(r), method: :delete %>
    </div>
    <br><br>
<%end%>

lab_7/WebLab/app/views/reports/new.html.erb
<center>
    <h2> Добавление отчета </h2>

    <%ects_grades = [nil,'A (100-90)','B (89-82)','C (81-75)','D (74-69)','E (68-60)','FX (59-35)','F (34-1)']%>

    <%=form_with model: @report do |f|%>
        <%= f.hidden_field :user_id, value: current_user.id %>
        <%=f.label :title, 'Заголовок'%><br>
        <%=f.text_field :title%><br>
        <%=f.label :description, 'Текст'%><br>
        <%=f.text_area :description, rows: 5%><br>
        <%=f.label :grade, 'Оценка'%><br>
        <%=f.select :grade, ects_grades%><br><br>
        <%=f.submit '+ Добавить работу'%>
    <%end%>
</center>
<br><br>
<%=button_to '⇐ Отмена', reports_path, method: :get%>

lab_7/WebLab/app/views/users/new.html.erb
<div align="center">
    <h1>Регистрация пользователя</h1>
    <%= form_with model: @user, url: users_path do |f|%>
        <%= f.label :first_name, 'Имя'%>
        <%= f.text_field :first_name %>
        <br>
        <%= f.label :last_name, 'Фамилия'%>
        <%= f.text_field :last_name %>
        <br>
        <%= f.label :email, 'E-mail'%>
        <%= f.email_field :email %>
        <br>
        <%= f.label :password, 'Пароль'%>
        <%= f.password_field :password%>
        <br>
        <%= f.submit 'Зарегистрировать'%>
    <% end %>
</div>
<br>
<%= button_to '⇐ На Главную', root_path, method: :get %>